
package com.example.ws.soap.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.ws.deepakbhalla.CreateOrdersRequest;
import com.ws.deepakbhalla.CreateOrdersResponse;
import com.ws.deepakbhalla.GetOrdersRequest;
import com.ws.deepakbhalla.GetOrdersResponse;
import com.ws.deepakbhalla.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerOrdersPortType", targetNamespace = "http://www.deepakbhalla.ws.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerOrdersPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.ws.deepakbhalla.CreateOrdersResponse
     */
    @WebMethod(action = "http://www.deepakbhalla.ws.com/createOrders")
    @WebResult(name = "createOrdersResponse", targetNamespace = "http://www.deepakbhalla.ws.com", partName = "parameters")
    public CreateOrdersResponse createOrders(
        @WebParam(name = "createOrdersRequest", targetNamespace = "http://www.deepakbhalla.ws.com", partName = "parameters")
        CreateOrdersRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ws.deepakbhalla.GetOrdersResponse
     */
    @WebMethod(action = "http://www.deepakbhalla.ws.com/getOrders")
    @WebResult(name = "getOrdersResponse", targetNamespace = "http://www.deepakbhalla.ws.com", partName = "parameters")
    public GetOrdersResponse getOrders(
        @WebParam(name = "getOrdersRequest", targetNamespace = "http://www.deepakbhalla.ws.com", partName = "parameters")
        GetOrdersRequest parameters);

}
