
package com.deepak.ws.soap;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentProcessorImplService", targetNamespace = "http://soap.ws.deepak.com/", wsdlLocation = "META-INF/wsdl/PaymentProcessorImplService.wsdl")
public class PaymentProcessorImplService
    extends Service
{

    private final static URL PAYMENTPROCESSORIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYMENTPROCESSORIMPLSERVICE_EXCEPTION;
    private final static QName PAYMENTPROCESSORIMPLSERVICE_QNAME = new QName("http://soap.ws.deepak.com/", "PaymentProcessorImplService");

    static {
        PAYMENTPROCESSORIMPLSERVICE_WSDL_LOCATION = com.deepak.ws.soap.PaymentProcessorImplService.class.getClassLoader().getResource("META-INF/wsdl/PaymentProcessorImplService.wsdl");
        WebServiceException e = null;
        if (PAYMENTPROCESSORIMPLSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/PaymentProcessorImplService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PAYMENTPROCESSORIMPLSERVICE_EXCEPTION = e;
    }

    public PaymentProcessorImplService() {
        super(__getWsdlLocation(), PAYMENTPROCESSORIMPLSERVICE_QNAME);
    }

    public PaymentProcessorImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTPROCESSORIMPLSERVICE_QNAME, features);
    }

    public PaymentProcessorImplService(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTPROCESSORIMPLSERVICE_QNAME);
    }

    public PaymentProcessorImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTPROCESSORIMPLSERVICE_QNAME, features);
    }

    public PaymentProcessorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentProcessorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentProcessor
     */
    @WebEndpoint(name = "PaymentProcessorImplPort")
    public PaymentProcessor getPaymentProcessorImplPort() {
        return super.getPort(new QName("http://soap.ws.deepak.com/", "PaymentProcessorImplPort"), PaymentProcessor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentProcessor
     */
    @WebEndpoint(name = "PaymentProcessorImplPort")
    public PaymentProcessor getPaymentProcessorImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.ws.deepak.com/", "PaymentProcessorImplPort"), PaymentProcessor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTPROCESSORIMPLSERVICE_EXCEPTION!= null) {
            throw PAYMENTPROCESSORIMPLSERVICE_EXCEPTION;
        }
        return PAYMENTPROCESSORIMPLSERVICE_WSDL_LOCATION;
    }

}
